apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: formrenders.fuxi.nip.io
spec:
  group: fuxi.nip.io
  names:
    kind: FormRender
    listKind: FormRenderList
    plural: formrenders
    singular: formrender
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: FormRender is the Schema for the formrenders API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the clientv1
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FormRenderSpec defines the desired state of FormRender
          properties:
            id:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            props_schema:
              type: string
            ui_schema:
              type: string
          required:
          - id
          type: object
        status:
          description: FormRenderStatus defines the observed state of FormRender
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
