apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: forms.fuxi.nip.io
spec:
  group: fuxi.nip.io
  names:
    kind: Form
    listKind: FormList
    plural: forms
    singular: form
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Form is the Schema for the forms API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FormSpec defines the desired state of Form
            properties:
              props_schema:
                type: string
              tree:
                items:
                  properties:
                    children:
                      items: {}
                      type: array
                    key:
                      type: string
                    node_type:
                      type: string
                    title:
                      type: string
                  required:
                  - children
                  - key
                  - node_type
                  - title
                  type: object
                type: array
            required:
            - props_schema
            - tree
            type: object
          status:
            description: FormStatus defines the observed state of Form
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
