apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pages.fuxi.nip.io
spec:
  group: fuxi.nip.io
  names:
    kind: Page
    listKind: PageList
    plural: pages
    singular: page
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Page is the Schema for the pages API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PageSpec defines the desired state of Page
            properties:
              form_list:
                items:
                  type: string
                type: array
              id:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
            required:
            - id
            type: object
          status:
            description: PageStatus defines the observed state of Page
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
