apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: baseusers.fuxi.nip.io
spec:
  group: fuxi.nip.io
  names:
    kind: BaseUser
    listKind: BaseUserList
    plural: baseusers
    singular: baseuser
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
